import numpy as np
import onnxruntime as ort
from onnxruntime.quantization import CalibrationDataReader


class DataReader(CalibrationDataReader):

    def __init__(self, model_path, npz_path):
        self.model_path = model_path
        self.npz_path = npz_path

        # ---------------------------------------------------------
        # Load the ONNX model to get the exact input name and shape
        # ---------------------------------------------------------
        session = ort.InferenceSession(
            model_path,
            providers=["CPUExecutionProvider"]
        )

        model_input = session.get_inputs()[0]

        self.input_name = model_input.name
        self.input_shape = model_input.shape

        print("Model input name :", self.input_name)
        print("Model input shape:", self.input_shape)

        # ---------------------------------------------------------
        # Load calibration data
        # ---------------------------------------------------------
        data = np.load(npz_path)

        print("\nContents of calibration NPZ:")
        for key in data.files:
            print("  ", key, data[key].shape, data[key].dtype)

        # ---------------------------------------------------------
        # Find calibration data
        #
        # Usually train.npz generated by Keras/NumPy will contain
        # something such as:
        #
        #   x
        #   y
        #
        # or:
        #
        #   X
        #   y
        #
        # We only need the input features.
        # ---------------------------------------------------------

        if "x" in data.files:
            self.calibration_data = data["x"]

        elif "X" in data.files:
            self.calibration_data = data["X"]

        else:
            # If there is only one array, use it.
            if len(data.files) == 1:
                self.calibration_data = data[data.files[0]]
            else:
                raise ValueError(
                    "Could not determine the input data in train.npz. "
                    f"Available arrays: {data.files}"
                )

        print("\nCalibration data:")
        print("  Shape :", self.calibration_data.shape)
        print("  Dtype :", self.calibration_data.dtype)

        # ---------------------------------------------------------
        # Calibration data must be FP32 for ONNX Runtime
        # ---------------------------------------------------------
        self.calibration_data = self.calibration_data.astype(
            np.float32
        )

        # ---------------------------------------------------------
        # Create iterator
        # ---------------------------------------------------------
        self.enum_data = None

    def get_next(self):
        """
        Return one calibration sample at a time.
        """

        if self.enum_data is None:
            self.enum_data = iter(self.calibration_data)

        try:
            sample = next(self.enum_data)
        except StopIteration:
            return None

        # ---------------------------------------------------------
        # Make sure sample has the same shape expected by model.
        #
        # For example:
        #
        # train.npz:
        #     (N, 650)
        #
        # model:
        #     [1, 650]
        #
        # We add the batch dimension when necessary.
        # ---------------------------------------------------------

        sample = np.asarray(sample, dtype=np.float32)

        expected_rank = len(self.input_shape)

        if sample.ndim == expected_rank - 1:
            sample = np.expand_dims(sample, axis=0)

        return {
            self.input_name: sample
        }

    def rewind(self):
        """
        Reset the calibration data iterator.
        """
        self.enum_data = iter(self.calibration_data)